# Generated by Django 5.0.1 on 2024-01-08 14:14

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EachItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('pay_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('cardholder_name', models.CharField(max_length=255)),
                ('expiration_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('billing_address', models.TextField()),
                ('card_type', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='product/')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('freeDelivery', models.BooleanField(default=True)),
                ('specification', models.JSONField(blank=True)),
                ('specification_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('dpid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.address')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ordered_products', models.ManyToManyField(to='home.eachitem')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_charges', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_type', models.CharField(blank=True, choices=[('Regular Delivery', 'Regular Delivery'), ('Instant Delivery', 'Instant Delivery')], null=True)),
                ('status', models.CharField(choices=[('Out for Delivery', 'Out for Delivery'), ('Placed', 'Placed'), ('Dispatched', 'Dispatched'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Processing', 'Processing'), ('On Hold', 'On Hold'), ('Returned', 'Returned'), ('Completed', 'Completed')])),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'Online Payment'), ('Card', 'Credit/Debit Card'), ('EMI', 'EMI')])),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('delivery_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.deliverypartner')),
                ('ordered_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.products')),
            ],
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='orders_handling',
            field=models.ManyToManyField(related_name='order_handling_partners', to='home.orders'),
        ),
        migrations.AddField(
            model_name='eachitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.products'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('referal', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profilePic/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
                ('doj', models.DateTimeField(auto_now_add=True)),
                ('last_OTP', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)])),
                ('OTP_sent_time', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Business Leader', 'Business Leader'), ('Team Manager', 'Team Manager'), ('Regional Manager', 'Regional Manager'), ('General Manager', 'General Manager')], default='Customer', max_length=50)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.address', verbose_name='Address')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cart')),
                ('down_leaf', models.ManyToManyField(blank=True, null=True, to='home.users')),
                ('payment_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.paymentdetails')),
                ('wishlist', models.ManyToManyField(blank=True, to='home.products')),
            ],
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.users'),
        ),
        migrations.AddField(
            model_name='eachitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.users'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='home.users'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='home.users', verbose_name='User_Address'),
        ),
    ]
