# Generated by Django 5.0.1 on 2024-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_products_tag_alter_users_down_leaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='CFM',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
