# Generated by Django 5.0.1 on 2024-01-16 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='earning',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('General Manager', 'General Manager'), ('Regional Manager', 'Regional Manager'), ('Team Manager', 'Team Manager'), ('Business Leader', 'Business Leader'), ('Customer', 'Customer')], default='Customer', max_length=50),
        ),
    ]
