# Generated by Django 5.0.1 on 2024-01-16 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_earning_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='earning',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10),
        ),
    ]
