# Generated by Django 5.0.1 on 2024-01-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_users_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='CFM',
        ),
        migrations.AddField(
            model_name='products',
            name='BLE',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='GME',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='RME',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='products',
            name='TME',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
