# Generated by Django 5.0.1 on 2024-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_products_cfm_products_ble_products_gme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='BLE',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='GME',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='RME',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='TME',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
